import {
  jsonArrayFrom,
  jsonObjectFrom,
} from "kysely/helpers/postgres"
import { query_builder } from "~/lib/server/query_builder"

export async function fetch_property(id: number) {
  return query_builder
    .selectFrom("property")
    .innerJoin(
      "location",
      "location.id",
      "property.location_id",
    )
    .innerJoin(
      "property_type_department",
      "property_type_department.property_id",
      "property.id",
    )
    .select((eb) => [
      "property.id",
      "property.created_at",
      "property_type_department.unit",
      "property_type_department.floor",
      jsonArrayFrom(
        eb
          .selectFrom("room")
          .select([
            "room.id",
            "room.type",
            "room.width",
            "room.length",
          ])
          .whereRef("room.property_id", "=", "property.id"),
      ).as("rooms"),
      jsonObjectFrom(
        eb
          .selectFrom("location")
          .select([
            "location.address",
            "location.id",
            "location.latitude",
            "location.longitude",
            "location.road",
            "location.house_number",
            "location.state",
            "location.suburb",
            "location.city",
            "location.town",
          ])
          .whereRef(
            "location.id",
            "=",
            "property.location_id",
          ),
      )
        .$notNull()
        .as("location"),
      jsonArrayFrom(
        eb
          .selectFrom("contract")
          .select((eb) => [
            "contract.id",
            "contract.start_date",
            "contract.end_date",
            "contract.state",
            "contract.duration",
            "contract.formula",
            jsonArrayFrom(
              eb
                .selectFrom("period")
                .innerJoin(
                  "contract",
                  "contract.id",
                  "period.contract_id",
                )
                .select([
                  "period.id",
                  "period.price",
                  "period.start_date",
                  "period.end_date",
                ])
                .whereRef(
                  "period.contract_id",
                  "=",
                  "contract.id",
                ),
            ).as("periods"),
            eb
              .selectFrom("period")
              .select("period.price")
              .whereRef(
                "period.contract_id",
                "=",
                "contract.id",
              )
              .orderBy("period.created_at", "asc")
              .limit(1)
              .as("initial_price"),
            jsonArrayFrom(
              eb
                .selectFrom("contract_file")
                .innerJoin(
                  "file",
                  "file.id",
                  "contract_file.file_id",
                )
                .select([
                  "file.basename",
                  "file.id",
                  "contract_file.type",
                ])
                .whereRef(
                  "contract_file.contract_id",
                  "=",
                  "contract.id",
                ),
            ).as("files"),
          ])
          .whereRef(
            "contract.property_id",
            "=",
            "property.id",
          ),
      ).as("contracts"),
      jsonArrayFrom(
        eb
          .selectFrom("service")
          .select([
            "service.id",
            "service.code",
            "service.type",
          ])
          .whereRef(
            "service.property_id",
            "=",
            "property.id",
          ),
      ).as("services"),
    ])
    .where("property.id", "=", id)
    .executeTakeFirst()
}
export type Property = NonNullable<
  Awaited<ReturnType<typeof fetch_property>>
>
