storage:
  type: memory

ui:
  title: Habita Status
  header: Habita Services

endpoints:
  - name: Website
    group: Core
    url: "http://svelte:3000/health"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: Database
    group: Core
    url: "tcp://db:5432"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"

  - name: Cache (Valkey)
    group: Core
    url: "tcp://kv:6379"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"

  - name: API (Go)
    group: Services
    url: "http://go:8081/health"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"

  - name: Image Proxy
    group: Services
    url: "http://image:8080/health"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"

  - name: Geocoding
    group: Services
    url: "http://nominatim:8080/status"
    interval: 60s
    ui:
      hide-hostname: true
    conditions:
      - "[STATUS] == 200"

  - name: Gateway
    group: Infrastructure
    url: "http://caddy:80"
    interval: 30s
    ui:
      hide-hostname: true
    conditions:
      - "[STATUS] < 500"
