export const ACTION = {
  UPDATE_CONTRACT: "update_contract",
  CREATE_FILE: "create_file",
  DESTROY_FILE: "destroy_file",
  CREATE_PDF: "create_pdf",
  CREATE_CONTRACT_ITEM: "create_contract_item",
  UPDATE_CONTRACT_ITEM: "update_contract_item",
  DESTROY_CONTRACT_ITEM: "destroy_contract_item",
  CREATE_CONTRACT_ITEM_FILE: "create_contract_item_file",
  DESTROY_CONTRACT_ITEM_FILE: "destroy_contract_item_file",
  UPDATE_PERIOD: "update_period",
  CREATE_PERIOD: "create_period",
  CREATE_WARRANTY: "create_warranty",
  UPDATE_WARRANTY: "update_warranty",
  ADD_INCOME_GUARANTOR: "add_income_guarantor",
  UPDATE_INCOME_GUARANTOR: "update_income_guarantor",
  DESTROY_INCOME_GUARANTOR: "destroy_income_guarantor",
  CHECK_CERTIFICATES: "check_certificates",
  START_ONBOARDING: "start_onboarding",
  SEND_FOR_SIGNING: "send_for_signing",
  VERIFY_SIGNATURE: "verify_signature",
} as const
