services:
  nominatim:
    image: mediagis/nominatim:4.4
    ports:
      - "8090:8090"
    environment:
      - PBF_URL=https://download.geofabrik.de/south-america/argentina-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/south-america/argentina-updates/
      - IMPORT_WIKIPEDIA=false
      - IMPORT_US_POSTCODES=false
      - IMPORT_GB_POSTCODES=false
      - NOMINATIM_LISTEN_PORT=8090
    volumes:
      - nominatim:/var/lib/postgresql/14/main
    shm_size: 1gb
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  nominatim:
