services:
  go:
    build:
      context: ../../apps/go
      dockerfile: Dockerfile
      pull: false
      x-bake:
        provenance: false
    volumes:
      - ../../apps/go:/apps/go
    env_file:
      - ../.env.dev
    environment:
      OTEL_ENVIRONMENT: development
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "1.0"
        reservations:
          memory: 128M
          cpus: "0.25"
