services:
  go:
    image: niconiahi/habita:go-${GO_TAG:?GO_TAG required}
    env_file:
      - ../.env.prod
    environment:
      OTEL_ENVIRONMENT: production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.25"
