import type { Props } from "~/lib/contract/pdf.server"

export function SectionEighteen({
  contract,
}: {
  contract: Props
}) {
  return `[FIADORES] se constituyen en calidad de fiadores solidarios, codeudores liso, llano y principales pagadores, renunciado en este acto a los beneficios de excusión y división a los efectos de su directa responsabilidad por todos los importes que adeude "EL LOCATARIO" con motivo de las obligaciones emergentes de la ley o el presente contrato, durante el término de su vigencia y con posterioridad a su vencimiento, hasta la efectiva restitución del inmueble a "EL LOCADOR" y hasta tanto se hubieren cancelado todas y cada una de las obligaciones emergentes de la relación locativa. En este caso, el hecho de no dar aviso a "LOS FIADORES" ni demandar, no importa prórroga de cualquier plazo, a "EL LOCATARIO" ni a "LOS FIADORES", no extingue la garantía. Especialmente se establece que "LOS FIADORES" responderán si por cualquier disposición legal futura que "EL LOCADOR" se viera obligado a tolerar una prórroga de la locación en cualquier condición. Asimismo, se extenderá su responsabilidad a las costas, gastos y honorarios que pudieran devengar con motivo de cualquier reclamo judicial o extrajudicial que a raíz de este contrato se viera precisado a iniciar "EL LOCADOR", ya sea por desalojo, cobro de alquileres, cobro de reparaciones, indemnizaciones y/o multas. En caso de muerte, insolvencia, disminución sustancial de patrimonio, quiebra, incapacidad o cambio de domicilio de "LOS FIADORES", "EL LOCATARIO" deberá informar el hecho al "EL LOCADOR" dentro de las 48 horas posteriores a su acaecimiento por cualquier medio fehaciente, y sustituirlo a satisfacción de "EL LOCADOR" en el plazo improrrogable de treinta (30) días corridos, contados desde la fecha de notificación. El no cumplimiento de dicha intimación en plazo, faculta a "EL LOCADOR" para disolver el contrato por causa imputable a "EL LOCATARIO", quedando expedita la vía de desalojo y demás acciones correspondientes.`
}
