import type { Props } from "~/lib/contract/pdf.server"

export function SectionFourteen({
  contract,
}: {
  contract: Props
}) {
  return `Salvo aquellos casos en los que la mora se pacta en forma automática, en caso de incumplimiento la parte cumplidora deberá emplazar por el término de 72 hs a la otra, a efectos de cesar en el incumplimiento. Vencido el plazo sin que el incumplimiento haya cesado, si el incumplimiento corresponde a "EL LOCATARIO", sin perjuicio de las penalidades que puedan establecerse para cada caso, "EL LOCADOR" podrá demandar judicialmente por el cumplimiento de este contrato o resolverlo por culpa de "EL LOCATARIO", y solicitar el inmediato desalojo de este o quienes ocupen el inmueble. En ambos casos y para el evento de que "EL LOCATARIO" dejare abandonada la unidad o depositare judicialmente las llaves, deberá abonar a "EL LOCADOR" una multa equivalente al alquiler pactado, hasta el día en que "EL LOCADOR" recupere la libre y efectiva tenencia definitiva de la propiedad, debiendo indemnizarlo también por los eventuales daños y perjuicios sufridos. Se establece este derecho para "EL LOCADOR" en forma especial en el caso de la falta de pago de dos (2) mensualidades de alquiler. FALTA DE PAGO: a) El simple vencimiento del plazo pactado para el pago de los alquileres y/o servicios constituirá en mora a "EL LOCATARIO" de pleno derecho, sin necesidad de interpelación judicial o extrajudicial alguna y dará origen a la multa a favor de "EL LOCADOR" por cada día transcurrido desde el día siguiente al del vencimiento de la obligación incumplida y hasta el día de su efectivo pago, sin perjuicio del interés compensatorio que corresponda y otras acciones legales contra "EL LOCATARIO" que pudieran corresponder, b) Si "EL LOCATARIO" dejara de abonar el alquiler, y/o servicios en la forma prevista o faltara a cualquiera de las obligaciones que le impone el presente contrato sin causa alguna, sin perjuicio de la intimación que al efecto pueda formularle "EL LOCADOR", este podrá reclamar el desalojo con más los daños y perjuicios correspondientes.`
}
