creation_rules:
  - path_regex: infra/\.env\.dev(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1pu9kh335n2utmkxw0xequ8yru4thryt7cqkya369q6c04an7vqtqeha9z9
  - path_regex: infra/\.env\.prod(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1pu9kh335n2utmkxw0xequ8yru4thryt7cqkya369q6c04an7vqtqeha9z9
  - path_regex: infra/scheduler/rclone\.conf(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1pu9kh335n2utmkxw0xequ8yru4thryt7cqkya369q6c04an7vqtqeha9z9
