creation_rules:
  - path_regex: infra/development/\.env(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1f7tyg3s2y3qrjc6m752zmsmq2avc6yyrrrhs7p50f49qt893s3msp2w5fk
  - path_regex: infra/production/\.env(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1f7tyg3s2y3qrjc6m752zmsmq2avc6yyrrrhs7p50f49qt893s3msp2w5fk
  - path_regex: infra/production/scheduler/rclone\.conf(\.enc)?$
    age: age1s29vyugtakkf2lmj38jxgqssf044j2gh6fg47yx48hh8hazz0vuspj8ayx,age1f7tyg3s2y3qrjc6m752zmsmq2avc6yyrrrhs7p50f49qt893s3msp2w5fk
