export const ACTION = {
  UPDATE_LOCATION: "update_location",
  CREATE_FLOOR: "create_floor",
  UPDATE_FLOOR: "update_floor",
  DESTROY_FLOOR: "destroy_floor",
  CREATE_ROOM: "create_room",
  UPDATE_ROOM: "update_room",
  UPDATE_ROOM_POSITIONS: "update_room_positions",
  DESTROY_ROOM: "destroy_room",
  CREATE_SERVICE: "create_service",
  UPDATE_SERVICE: "update_service",
  DESTROY_SERVICE: "destroy_service",
  CREATE_PROPERTY_FILE: "create_property_file",
  INVITE_LANDLORD: "invite_landlord",
  UPDATE_DESTINIES: "update_destinies",
  TOGGLE_TAG: "toggle_tag",
  UPDATE_CONSTRUCTION_YEAR: "update_construction_year",
  REORDER_FLOORS: "reorder_floors",
} as const
