upstream query-service {
    server query-service:8080;
}

server {
    listen 3301;

    location /api {
        proxy_pass http://query-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
